"""Defaults."""

BATCH_SIZE = 32

REVERSE_EDITS = True

ENCODER = "bert-base-multilingual-cased"
ENCODER_DROPOUT = 0.5
ENCODER_LEARNING_RATE = 5e-3
POOLING_LAYERS = 4

CLASSIFIER_DROPOUT = 0.3
CLASSIFIER_LEARNING_RATE = 2e-5

WARMUP_STEPS = 500

USE_UPOS = True
USE_XPOS = True
USE_LEMMA = True
USE_FEATS = True
